//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHotelProject2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pagamentos> Pagamentos { get; set; }
        public virtual DbSet<Quartos> Quartos { get; set; }
        public virtual DbSet<QuartosReservados> QuartosReservados { get; set; }
        public virtual DbSet<PagamentosTipo> PagamentosTipo { get; set; }
        public virtual DbSet<QuartosTipo> QuartosTipo { get; set; }
        public virtual DbSet<ReservaStatus> ReservaStatus { get; set; }
    }
}
