//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHotelProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuartosReservados
    {
        public int ReservaId { get; set; }
        public string ClienteNome { get; set; }
        public string ClienteEndereco { get; set; }
        public System.DateTime ReservadoDataInicial { get; set; }
        public System.DateTime ReservaDataFinal { get; set; }
        public int QuartoReservadoId { get; set; }
        public int QuantidadePessoas { get; set; }
    }
}
