//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheHotelProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaStatus
    {
        public int ReservaStatusId { get; set; }
        public string ReservaStatus1 { get; set; }
    }
}
